### ISSUE TITLE
Documentation on how to pass parameters to templates in standalone mode

### ISSUE THREAD

**Issue by dhasenan** [bausshf/Diamond#1]
I don't see any documentation on how to pass parameters to a template in standalone mode. The example doesn't even have a model. The other examples seem to have layers of abstraction and convenience in the way, so I can't get the information from them.

**Comment by bausshf** [comment]
You can pass models in the same way as web templates.

Ex. for the example project already given:

```
module main;

import diamondapp;
import models;

void main() {
  import std.stdio;

  auto model = MyModel(); // The view must implement the model metadata
  auto view = getView("test");

  writeln(view.generate(model)); // Passing the model to the view
  readln();
}
```

And for the model metadata, place this at the top of the view

```
@[
  model:
    Home
]
```
